# filename: netlify.toml
# Static hosting with API proxy to Railway + Edge auth for /formular/*

[edge_functions]
  directory = "edge-functions"

[[edge_functions]]
  path = "/formular/*"
  function = "require-auth"

[[redirects]]
  from = "/api/*"
  to   = "https://make-ki-backend-neu-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/healthz"
  to   = "https://make-ki-backend-neu-production.up.railway.app/healthz"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to   = "https://make-ki-backend-neu-production.up.railway.app/health"
  status = 200
  force = true

[[redirects]]
  from = "/metrics"
  to   = "https://make-ki-backend-neu-production.up.railway.app/metrics"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
