[build]
  command = ""
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

# In local dev (`netlify dev`), functions run on this port
[dev]
  functionsPort = 9999

# Proxy all /api/* requests through the Netlify function.
# The function will forward the request to your Railway backend as set in the BACKEND_ORIGIN env var.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

# Conservative security headers (kept permissive for typical SPA needs)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP: allow self + inline styles/scripts typical for simple static sites; you can tighten later.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
