[build]
  publish = "."

# Edge-Funktionen: Login & Verify laufen auf Netlify (kein Upstream nötig)
[[edge_functions]]
  function = "login"
  path = "/api/login"

[[edge_functions]]
  function = "verify"
  path = "/api/auth/verify"

# Alle anderen API-Routen gehen ins Railway-Backend
[[redirects]]
  from = "/api/*"
  to   = "https://make-ki-backend-neu-production.up.railway.app/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/healthz"
  to   = "https://make-ki-backend-neu-production.up.railway.app/healthz"
  status = 200
  force  = true

[[redirects]]
  from = "/metrics"
  to   = "https://make-ki-backend-neu-production.up.railway.app/metrics"
  status = 200
  force  = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
