[build]
  publish = "."

[functions]
  node_bundler = "esbuild"

# Proxy zu Railway
[[redirects]]
  from = "/api/*"
  to   = "https://make-ki-backend-neu-production.up.railway.app/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/healthz"
  to   = "https://make-ki-backend-neu-production.up.railway.app/healthz"
  status = 200
  force  = true

[[redirects]]
  from = "/metrics"
  to   = "https://make-ki-backend-neu-production.up.railway.app/metrics"
  status = 200
  force  = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# Keep Railway warm alle 2 Minuten
[[scheduled.functions]]
  name = "keepalive"
  cron = "*/2 * * * *"
