# filename: netlify.toml
# Statisches Frontend mit API-Proxy zu Railway (kein publish/build erzwungen).

# --- API-Proxy: alle /api/* Calls zum Railway-Backend ---
[[redirects]]
  from = "/api/*"
  to   = "https://make-ki-backend-neu-production.up.railway.app/api/:splat"
  status = 200
  force = true

# --- Health/Debug explizit (inkl. /healthz) ---
[[redirects]]
  from = "/healthz"
  to   = "https://make-ki-backend-neu-production.up.railway.app/healthz"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to   = "https://make-ki-backend-neu-production.up.railway.app/health"
  status = 200
  force = true

[[redirects]]
  from = "/metrics"
  to   = "https://make-ki-backend-neu-production.up.railway.app/metrics"
  status = 200
  force = true

# Optional: API-Header härten (Caching aus, CORS regeln wir nicht hier, weil Same-Origin via Proxy)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

